lib/sidebar/component.json, lib/sidebar/filter-container.jade, lib/sidebar/filter.js, lib/sidebar/list-item.jade, lib/sidebar/list.js, lib/sidebar/sidebar.js
This is a refactor for `sidebar:list` and `sidebar:filter`
=> [sidebar] - Refactor to extend from View #282

lib/translations/lib/uk.json
I've realized there were new updates to en.json recently not captured in the uk.json submitted yesterday. I've realigned them again and corrected some syntax errors.
=> adjusted uk.json based on the recent changes to en.json

lib/jwt/index.js, lib/setup/index.js, lib/utils/index.js
=> Fixed req.user null reference when route does not use restrict middleware

lib/comment-card/styles.styl, lib/comment-card/template.jade, lib/comment-card/view.js, lib/comment-vote/view.js, lib/proposal-options/proposal-options.styl, lib/proposal-options/template.jade
This is a quick solution that works. Code refactor required.
=> Call for login messages placed over action buttons. Closes #592 and #593.

lib/boot/boot.js, lib/jwt/component.json, lib/jwt/jwt.js, lib/store/component.json, lib/store/index.js, lib/store/storages/cookie.js, lib/store/storages/localStorage.js, lib/store/storages/remote.js, lib/store/store.js
* Improved lib/store to be able to use localStorage thru https://github.com/marcuswestin/store.js/, also added the possibilty to select fallbacks and order of them (cookies or remote session).
* Implemented on lib/jwt component.
=> Wrap localstorage #582

lib/translations/lib/nl.json
Improved some Dutch translations.
=> Some updates to Dutch translation.

lib/comment/index.js, lib/proposal-clauses/proposal-clauses.js, lib/translations/lib/en.json
This is the server-side aspect of #577, see pull [#5](https://github.com/DemocracyOS/side-comments/pull/5) on side-comments component for client side.
=> Allow in-app editing of side comments

lib/404/404.js, lib/boot/boot.js
=> fix error after login

lib/law-api/index.js
See https://github.com/DemocracyOS/notifier/pull/27 as well
=> [law-api] - Add instanceUrl and law.id to data sent to notifier #673

index.js
=> Fixed app crashing in HTTPS mode

lib/models/user.js, lib/registration/index.js, lib/signup-api/lib/signup.js
Now the app queries the HTTPS endpoint of gravatar when HTTPS is enabled.
Closes #711.
=> Fixed gravatar request in HTTPS

lib/db-api/law.js, lib/models/law.js, lib/proposal-article/proposal-article.js, lib/richtext/richtext.js
=> Fix richtext formatting

lib/proposal-clauses/proposal-clauses.js
=> Fixed saved side comments not being shown

lib/citizen/model.js, lib/comment-card/template.jade, lib/comment-card/view.js, lib/comment/index.js, lib/comments-replies/comments-reply.jade, lib/db-api/comment.js, lib/db-api/user.js, lib/jwt/index.js, lib/law-api/index.js, lib/models/user.js, lib/participant-view/template.jade, lib/proposal-clauses/proposal-clauses.js
=> Fixed user image not shown

lib/boot/boot.styl
=> Added tip and datepicker dep CSS

config/defaults.json, lib/proposal-options/proposal-options.js, lib/proposal-options/template.jade
=> add showResults config key and check it in proposal-options, closes #926

lib/db-api/comment.js, lib/db-api/user.js
=> Fixed queries not fetching profilePictureUrl

lib/db-api/comment.js, lib/db-api/topic.js
=> Fixed comment-reply URL

config/defaults.json, lib/notifications/index.js, lib/server/index.js
Should be tested and accepted with:
* https://github.com/DemocracyOS/notifier/pull/7
* https://github.com/DemocracyOS/notifier-server/pull/44
=> Add nodemailer configuration for notifier

README.md
Automated code review tool: https://codeclimate.com/github/DemocracyOS/app/code
=> Added codeclimate badge

lib/comments-edit/component.json, lib/comments-edit/view.js, lib/comments-replies/component.json, lib/comments-replies/view.js, lib/comments-view/component.json, lib/comments-view/view.js, lib/is-in-viewport/component.json, lib/is-in-viewport/is-in-viewport.js, lib/scroll-to/component.json, lib/scroll-to/scroll-to.js
Ok, I went ahead and forked component/scroll-to, then changed the scroll functionality for comments and comment-replies. I hope everything it's ok.
What remains to be done is checking if the elements are off-screen to perform the action. I'll see if I can find something for that, but at least the scroll is working.
#659
=> Add Smooth scrolling

LICENSE.txt, README.md
You may copy, distribute and modify the software as long as you track changes/dates in source files. Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.
=> [license] - Update to GPL-3.0 license

lib/admin-topics-form/view.js
=> fixes #1066, clear closign add closes datepicker

lib/config/index.js, package.json
=> Fix notifications bug on Heroku

docs/coding-styles.md
=> Fixing typo in coding-styles.md (.js for .styl)

bin/dos-db, lib/fixtures/topics.json
`./lib/fixtures/topics.json` was in the old V1 format. It could not be loaded according to the steps in [the fixture instructions](https://github.com/DemocracyOS/democracyos/wiki/Load-fixtures), as explained in issue #1176.
This converts `topics.json` to the new format, following the steps in [`migrateV1`](https://github.com/DemocracyOS/democracyos/blob/master/lib/migrations/topic.js#L59).
After doing this, loading the fixtures causes the topic to load and display as expected.
Fixes #1176.
(Includes commit from #1172, which is needed for testing the loading of fixtures.)
=> Updating ./lib/fixtures/topics.json

lib/logout/logout.js
=> Temporarily fix logout state

lib/forum-router/create-router.js
=> Add default singleforum route

lib/validators/validators.js, package.json
=> Add valid-url

lib/signin/template.jade, lib/translations/lib/en.json, lib/translations/lib/es.json
=> Update signin label

config/defaults.json, lib/db-api/user.js, lib/forum-api/index.js, lib/forum-middlewares/index.js, lib/forum/forum.js, lib/newsfeed/forum-info.jade, lib/settings-forum/new-forum-button.jade, lib/settings-forum/template.jade, lib/settings/settings-container.jade, lib/user-badge/template.jade, lib/user/index.js
this implement restrict-forum-creation, so that branch is no longer needed
=> Add restricForumCreation config

config/defaults.json, docs/configuration.md, lib/setup/index.js, package.json
Free certificates for everyone!
=> Add certbot

lib/site/comment-card/view.js, lib/site/comments-replies/view.js
=> Sanitize markdown comments

package.json
=> add LICENSE field

lib/api-v2/comments/index.js, lib/api-v2/db-api/comments/index.js, lib/site/topic-layout/topic-article/comments/component.js, lib/site/topic-layout/topic-article/comments/connector.js, lib/site/topic-layout/topic-article/comments/list/component.js, lib/site/topic-layout/topic-article/comments/list/replies/component.js, lib/site/topic-layout/topic-article/comments/list/replies/form/component.js, lib/site/topic-layout/topic-article/comments/list/replies/list/component.js, lib/site/topic-layout/topic-article/comments/list/replies/list/styles.styl, lib/site/topic-layout/topic-article/comments/list/styles.styl
Add comment reply only using api-v2
=> Add comment replies

lib/site/form-async/index.js, lib/site/sign-in/component.js, lib/site/sign-up/component.js
Move signup validation to signup component
Update signin validation message
=> Update sign in/up validations

lib/site/header/component.js, lib/site/header/styles.styl, lib/site/header/user-badge/component.js, lib/site/home-forum/styles.styl, lib/site/home-multiforum/component.js, lib/site/home-multiforum/styles.styl, lib/site/layout/styles.styl, lib/site/topic-layout/sidebar/filter/styles.styl, lib/site/topic-layout/sidebar/styles.styl, lib/site/topic-layout/topic-article/styles.styl
General style corrections and responsive behaviour
=> Update site styles

lib/site/topic-layout/topic-article/comments/component.js, lib/site/topic-layout/topic-article/comments/connector.js, lib/site/topic-layout/topic-article/comments/list/component.js, lib/site/topic-layout/topic-article/comments/styles.styl
Adds a button to load more comments, can be tested on https://multi-staging-democracyos.herokuapp.com/prueba/topic/57e18a0035de6f0300ec5ad8
=> [add-react] Add comments pagination

lib/admin/admin-permissions/add-user-input/add-user-input.js, lib/api-v2/db-api/users/scopes.js, lib/api/settings/index.js, lib/db-api/user.js, lib/models/user.js, lib/settings/settings-user-badges/styles.styl, lib/settings/settings-user-badges/template.jade, lib/settings/settings-user-badges/view.js, lib/settings/settings/settings-container.jade, lib/settings/settings/settings.js, lib/site/topic-layout/topic-article/comments/form/styles.styl, lib/site/topic-layout/topic-article/comments/list/comment/header/component.js, lib/site/topic-layout/topic-article/comments/list/comment/header/styles.styl, lib/site/topic-layout/topic-article/comments/list/comment/replies/list/component.js, lib/site/topic-layout/topic-article/comments/list/comment/replies/list/header/component.js, lib/site/topic-layout/topic-article/comments/list/comment/replies/list/header/styles.styl, lib/site/topic-layout/topic-article/comments/list/comment/styles.styl, lib/site/topic-layout/topic-article/comments/order-by/component.js, lib/site/topic-layout/topic-article/comments/order-by/styles.styl, lib/site/topic-layout/topic-article/comments/styles.styl, lib/translations/lib/en.json, lib/translations/lib/es.json
Allow staff user to set a validated user badge.
=> Add user badge

lib/admin/admin-tags-form/template.jade, lib/admin/admin-tags/template.jade, lib/admin/admin-topics-form/template.jade, lib/admin/admin-topics/template.jade, lib/models/tag.js, lib/models/topic.js, lib/models/user.js, lib/settings/settings-password/template.jade, lib/settings/settings-profile/template.jade, lib/site/forgot/component.js, lib/site/sign-in/component.js, lib/site/sign-up/component.js
Add max length validation to all input text fields.
ADMIN:
- Tag
- Topic
SETTINGS:
- Profile
- Password
SITE:
- User forms (not logged)
- Topic
=> Update form validations

lib/api-v2/comments/index.js, lib/api-v2/db-api/comments/index.js, lib/api-v2/middlewares/index.js, lib/api-v2/middlewares/notifications.js, lib/models/notification.js, lib/stores/notification-store/notification-store.js
Add coment reply notifications using a notification middleware.
=> Add comment reply notification

docs/install.md
Following #1359, it seems that install steps would be better ordered like that.
Sorry for the dual PR, should have done it at once.
=> clarify installation steps order

lib/admin/admin-topics-form/styles.styl, lib/admin/admin-topics-form/tag-autocomplete/component.js, lib/admin/admin-topics-form/tag-autocomplete/styles.styl, lib/admin/admin-topics-form/template.jade, lib/admin/admin-topics-form/view.js, lib/api-v2/boot/index.js, lib/api-v2/comments/csv.js, lib/api-v2/forums/index.js, lib/api-v2/middlewares/forums.js, lib/api-v2/middlewares/topics.js, package.json
Add autocomplete feature using radix-trie.
Got some validation errors on topic edit after rebase.
=> Add better tags input

lib/api-v2/topics/index.js, lib/models/topic.js, migrations/1495224425289-add-participant-count.js
Create a new property in Topic schema participantsCount, and removing virtual participantsCount, to be able to sort by that property easily in current api.
=> add persistent participantsCount

lib/api-v2/boot/index.js, lib/api-v2/comments/index.js, lib/api-v2/forums/index.js, lib/api-v2/search/index.js, lib/api-v2/topics/index.js, lib/api/boot/version.js, lib/api/forgot/index.js, lib/api/forum/index.js, lib/api/notification/index.js, lib/api/settings/index.js, lib/api/signin/index.js, lib/api/signup/index.js, lib/api/tag/index.js, lib/api/topic/index.js, lib/api/whitelist/index.js, lib/jwt/index.js, lib/site/user/user.js, lib/stores/forum-store/forum-store.js, lib/user/index.js, lib/utils/index.js
`express deprecated res.json(status, obj): Use res.status(status).json(obj) instead`
=> Fix express deprecated warning

cms/db-api/community.js, cms/models/community.js, package-lock.json, package.json, test/cms/db-api/community.js
model, dp-api and test files for community
=> [v3] Add community model and db-api

client/custom-routes.js, client/rest-client.js, cms/api/settings.js, cms/components/admin.js, cms/components/settings.js, cms/db-api/settings.js, cms/models/setting.js, package-lock.json
Add edit panel of community settings. Update fields and functionality of it.
=> [v3] Add settings panel

client/custom-routes.js, cms/components/admin.js, cms/components/users.js
Add list of users to User panel
=> [v3] Add admin users panel

client/custom-routes.js, cms/components/admin.js, cms/components/navbar.js, reactions/api/reaction-rule.js, reactions/components/ClosingDateField.js, reactions/components/reaction-rule.js
* Now you can create Reaction Rules with the admin-on-rest panel.
* There is a custom Input Field for the **closing date** of a reaction rule, where you can define if the rule has a closing date (by setting a date) or null.
* Added routes in admin-on-rest sidebar
Issue from: #1494
=> [v3] Reactions rules admin

cms/api/settings.js, cms/db-api/settings.js, cms/models/setting.js, locales/en.json, locales/es.json, main/errors.js
POST request to /settings throws new custom error when a setting document has already been created.
=> [v3] Update db-api/settings

main/api.js, main/mongoose.js, reactions/api/reaction-vote.js, test/reactions/api/reaction-vote.js
Other changes:
* Fixed test issues with reaction vote
* Created API for reaction votes
* Create tests for reaction votes API
Running `npm run test`
```
/api/v1.0/reaction-vote
#post
✓ should create a reaction vote
#list
✓ should list all reaction votes
#get
✓ should get a reaction vote by id
#put
✓ should update a reaction vote
#delete
✓ should remove a reaction vote
```
=> [v3] Reaction Votes

client/custom-routes.js, cms/components/posts/post-routes.js, cms/components/settings/settings-edit.js, cms/components/settings/settings-routes.js, reactions/components/reactions-routes.js, users/components/users-routes.js
Adds files in each folder in order to make CustomRoutes modular.
=> [v3] Add modular custom routes

cms/api/posts.js, cms/db-api/settings.js, test/cms/api/posts.js, test/cms/api/settings.js, test/cms/db-api/settings.js
It fixes the tests in api/posts, api/settings, db-api/settings at last. <3
```
/api/v1.0/posts
#post
✓ should create a post (67ms)
#list
✓ should list all posts (74ms)
#get
✓ should get a post by id
#put
✓ should update a post
#delete
✓ should remove a post
/api/v1.0/settings
#post
✓ should create a setting
#list
✓ should list all settings
#get
✓ should get a setting by id
#put
✓ should update a setting
#delete
✓ should remove a setting
db-api.settings
#create
✓ should create a setting (41ms)
#get
✓ should get a setting
#update
✓ should update a setting
#remove
✓ should remove a setting
```
=> [v3] Fix settings & posts api tests.

reactions/api/reaction-rule.js, reactions/components/reaction-rule.js, reactions/db-api/reaction-rule.js, test/reactions/api/reaction-rule.js
It adds the ability to search for Reaction Rules by writing its name.
Also, db-api updates.
=> Adding search bar for Reaction Rule List. Closes #1518

lib/api-v2/comments/index.js, lib/api-v2/db-api/topics/index.js, lib/api-v2/topics/index.js, lib/models/forum/topics-attrs.js, lib/privileges/forum.js, lib/privileges/topic.js, lib/site/topic-layout/topic-article/cause/component.js, lib/site/topic-layout/topic-article/comments/component.js, lib/site/topic-layout/topic-article/comments/form/component.js, lib/site/topic-layout/topic-article/comments/list/comment/component.js, lib/site/topic-layout/topic-article/comments/list/comment/replies/component.js, lib/site/topic-layout/topic-article/comments/list/comment/replies/form/component.js, lib/site/topic-layout/topic-article/component.js, lib/site/topic-layout/topic-article/poll/component.js, lib/site/topic-layout/topic-article/vote/component.js
This PR migrates the privilege `forum.privileges.canVoteAndComment` to the topic and divides it in two, `topic.privileges.canVote` and `topic.privileges.canComment`
=> Refactor vote and comments privileges

client/site/components/page.js, client/site/components/register/register-form.js, pages/auth/callback.js, pages/auth/check-email.js, pages/auth/index.js, pages/index.js, pages/register.js, test/users/api/users.js, users/auth/functions.js, users/models/user.js
Adds firstLogin to User model: a boolean field that shows if it's the first time that user signs in at the platform.
Adds a register form after signing in if it's user first login.
=> Add user register

client/site/components/header.js, client/site/components/menu.js, client/site/components/post-card.js, client/site/components/profile/private-profile.js, client/site/components/profile/public-profile.js, client/site/components/read/post-layout.js, client/site/components/register/register-form.js, pages/post.js, pages/profile.js, static/global.css
Adds /profile page. If user is owner, shows PrivateProfile, if not shows PublicProfile.
Also, it adds profile link in navbar and adds name field in register form.
=> [v3] Add user profile page

client/admin/components/rest-client.js, client/site/components/browse/browse-card.js, client/site/components/browse/browse-filter.js, client/site/components/browse/browse-grid.js, client/site/components/post-card.js, cms/api/posts.js, cms/db-api/posts.js, pages/browse.js, pages/index.js, static/global.css
Adds /browse page.
It has a filter bar which can search post titles by words, filter by date ranges and sort by date.
Also, added filter by date and sort params to db-api /posts.
Obviously, it has a very basic layout which I hope we will make prettier soon.
=> [v3] Add/site browse

reactions/components/ClosingDateField.js, reactions/components/reaction-instance.js, reactions/components/reaction-rule.js, reactions/models/reaction-instance.js, reactions/models/reaction-rule.js, reactions/models/reaction-vote.js, test/reactions/api/reaction-instance.js, test/reactions/api/reaction-rule.js, test/reactions/api/reaction-vote.js, test/reactions/db-api/reaction-instance.js, test/reactions/db-api/reaction-rule.js, test/reactions/db-api/reaction-vote.js
Here is a new update for the models for reaction instances, rules and votes.
The update is gonna be helpful for making the cards for people to vote the reactions of a post.
Plus we needed to assign a "meta" field to vote, cause we might want to save more information related to the vote of a user
Added new AoR components to control the new fields
Also, tests are updated too!
=> [v3] Update Reaction Instances, Rules and Vote models + Updated AoR Components

main/index.js, nodemon.json, package-lock.json, package.json
Adds nodemon to watch server side changes.
Please, run `npm install` as it adds a new package :)
Nodemon config can be checked at `nodemon.json` file
=> [v3] Add nodemon

client/site/components/reactions/please-login-modal.js, client/site/components/reactions/post-reactions.js, client/site/components/reactions/results-like-reaction.js, client/site/components/reactions/vote-like-reaction.js, client/site/components/reactions/voting-closed-modal.js, client/site/components/read/post-layout.js, pages/post.js, reactions/api/reaction-vote.js, reactions/components/ClosingDateField.js, reactions/components/ReactionResult.js, reactions/components/reaction-instance.js, reactions/components/reaction-rule.js, services/reactions.js
Hi! I present you: "Vote a reaction"
It took me a while but It was a bit crucial to understand the flow. This closes #1555 
I will make a small summary:
- After creating your reaction rules (Like, the rules for a LIKE button, or a SUPPORT button, or a DISLIKE button) You can assign it to a new reaction instance. Make sure you have a post, and a reaction rule, and then create the instance. Give it a title, and some instruction or description so users can see what they are reacting to.
- After created, **Make sure you are logged in**. Still, if you are not logged in, the buttons will trigger a modal with a message asking you to sign up.
- Are you logged in now? Awesome! Now you can vote any reaction instance. You can create as many reaction instances as you want for a single post. Create as …
=> [v3] Vote a reaction

client/site/components/reactions/post-reactions.js, client/site/components/reactions/vote-like-reaction.js, cms/api/posts.js, cms/api/settings.js, locales/en.json, locales/es.json, main/api.js, main/errors.js, pages/profile.js, services/reactions.js, services/users.js, users/api/users.js
Adds three middlewares:
- isLoggedIn
- isAdmin
- isOwner
isLoggedIn and isAdmin return a 403 forbidden error if false
isOwner adds a boolean isOwner property to req object if the user is owner of a given profile id
Now, we need to know in which routes they are needed :)
=> [v3] Add users middleware. Closes #1570

client/site/components/header.js, client/site/components/menu.js, client/site/components/reactions/vote-like-reaction.js, main/index.js, pages/auth/callback.js, pages/browse.js, pages/index.js, pages/init-settings.js, pages/post.js, pages/profile.js, pages/register.js
Fix visibility of pages and components according to user auth and user role.
Pages checked:
- index
- admin
- post
- profile
- auth
Please, @guillecro pay special attention to the small changes I made in `vote-like-reaction.js` cause the component coudn't be rendered if user was not logged in. Hope everything is working fine now :)
=> Fix visibility in pages & components

client/site/components/header.js
Adds a search button in header.
It redirects to browse page with the given query in the text input.
Enjoy!
=> [v3] Add browse button. Closes #1582

client/site/components/profile/private-profile.js, client/site/components/profile/public-profile.js, pages/profile.js
If the user is owner of the profile showing on /pages, shows an 'edit' button.
=> [v3] Add edit button in profile

client/site/components/reactions/post-reactions.js, client/site/components/reactions/results-like-reaction.js, client/site/components/reactions/vote-like-reaction.js, main/errors.js, reactions/api/reaction-instance.js, reactions/api/reaction-rule.js, reactions/api/reaction-vote.js, reactions/db-api/reaction-instance.js, services/reactions.js, services/users.js, users/api/users.js, users/db-api/user.js
Added auth specifications for users, reactions service and reactions.
Closing #1579!
=> [v3] Auth specifications for users, reaction service, and reactions

.gitignore, cms/api/posts.js, main/logger.js, package-lock.json, package.json, reactions/api/reaction-instance.js, reactions/api/reaction-rule.js, reactions/api/reaction-vote.js, reactions/db-api/reaction-vote.js, services/reactions.js, services/users.js, test/cms/api/posts.js, test/cms/api/settings.js, test/cms/db-api/posts.js, test/cms/db-api/settings.js, test/reactions/api/reaction-instance.js, test/reactions/api/reaction-rule.js, test/reactions/api/reaction-vote.js, test/reactions/db-api/reaction-instance.js, test/reactions/db-api/reaction-rule.js, test/reactions/db-api/reaction-vote.js, test/services/reactions.js, test/users/api/users.js, test/users/db-api/user.js, test/users/utils.js, test/utils.js, users/api/users.js, users/auth/functions.js
Finished all the tests!
```
/api/v1.0/posts
> Ready on http://localhost:3000 [test]
As Anonymous
✓ should get csrfToken
✓ GET / should be able to get a list of all the posts
✓ POST / should not be able to create a post
✓ GET /:id should be able to get a post
✓ PUT /:id should not be able to modify a post
✓ DELETE /:id should not be able to delete a post
As Logged user
✓ should get csrfToken
✓ should log in
✓ the session should have a user object
✓ GET / should be able to get a list of all the posts
✓ POST / should not be able to create a post
✓ GET /:id should be able to get a post
✓ PUT /:id should not be able to modify a post
✓ DELETE /:id should not be able to delete a post
As an admin user
✓ should get csrfToken
✓ should log in
✓ the session should have a user object
✓ GET / should be …
```
=> [v3] Fix API & db-API tests for models

lib/site/topic-layout/topic-article/slider/component.js, lib/site/topic-layout/topic-article/slider/styles.styl
- Add option labels under the track
- Change the track color if positive/negative
- Some other minor css fixes
=> Improve slider component
