DemocracyOS/democracyos

- lib/db-api/comment.js
- lib/forgot-api/lib/forgotpassword.js
- lib/law-api/index.js
- lib/notifications/index.js
- lib/signup-api/lib/signup.js
- lib/translations/lib/ca.json
- lib/translations/lib/de.json
- lib/translations/lib/en.json
- lib/translations/lib/es.json
- lib/translations/lib/fi.json
- lib/translations/lib/fr.json
- lib/translations/lib/it.json
- lib/translations/lib/nl.json
- lib/translations/lib/pt.json
Provides a wrapper for `notifier-client` in the way of a simple decorator that wraps the `send` function and intercepts the low-level `ECONNREFUSED` error triggered when the `notifier` server is unreachable by the client and provides a higher level error with a localized text entry.
Whether the backend should answer with `200` or `500` for these cases is not clear to me; sometimes (`signin`) the response is `200` and some other times `forgot` it's `500`; I believe we should establish one single approach.
Client-side handling of errors caused by notifier being unreachable are out of scope for this PR.
> Notifier wrapper. Closes #560

- lib/db/index.js
- lib/models/user.js
- lib/setup/index.js
Allows properly using MongoDB replica sets. App recognizes setting from mongo URI and self-configures accordingly.
Only tested this by setting just `mongoUrl` or both `mongoUrl` and `mongoUsersUrl` to databases of the same kind (single + single / replSet + replSet).
Haven't tested it with the following hybrid setups: `mongoUrl` pointing to a single database and `mongoUsersUrl` pointing to a replicaSet, or viceversa.
> [setup/user] update usage of mongodb by adding the db module

- lib/homepage/component.json
- lib/homepage/create-first-law.jade
- lib/homepage/homepage.js
- lib/homepage/homepage.styl
- lib/homepage/no-laws.jade
- lib/translations/lib/ca.json
- lib/translations/lib/de.json
- lib/translations/lib/en.json
- lib/translations/lib/es.json
- lib/translations/lib/fi.json
- lib/translations/lib/fr.json
- lib/translations/lib/gl.json
- lib/translations/lib/it.json
- lib/translations/lib/nl.json
- lib/translations/lib/pt.json
- lib/translations/lib/ru.json
- lib/translations/lib/sv.json
- lib/translations/lib/uk.json
*2 things to notice:*
+ Had to change the styling of the "There are no topics to display" alert, because it looked like a button and was competing (and its not a button).
+ We're not being consistent with the wording, the button says "debate" and the alert says "topics".
> Add create my first debate button for staff members Closes #703

- lib/proposal-options/template.jade
Adds non breaking white space to the end of the period and " or".  Closes #717
> Fixes #717 typos in must be signed in text

- lib/comment-card/styles.styl
Fixes #715 where comments link text should line break as regular text.
> Changes comment-text anchor text to inline #715

- lib/browser-lock/locker.js
I could reproduce the issue by signin in and try to change law in sidebar. 
In `browser-lock` we are using a singleton instance of `cristiandouce/loading-lock` and in certain cases that instance is being unlocked twice, then crashes trying to remove a DOM element that no longer exists.
I added a wrapper in order to put a flag that indicates the state (`locked`/`unlocked`) and during `unlock` it checks that flag before trying to modify the DOM.
Closes #738.
> Fix broken spinner after signin

- lib/admin-laws-form/view.js
- lib/admin-laws/view.js
- lib/boot/boot.styl
> Fix `component/confirmation` styles and breaking `focus()` calling

- lib/translations/lib/es.json
The word "Registración" does not exist in Spanish. "Registro" is the right translation.
> Small fix to Spanish translation

- lib/build/css.js
- lib/build/js.js
- lib/build/settings.js
- package.json
Can be enabled using `--livereload` flag to the `gulp watch` command.
Requires a LiveReload client, like [this extension for Chrome](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei).
> Added LiveReload

- lib/homepage/homepage.js
Checking for `user.ready` (unncesary) was removed due to the `user.optional` middleware.
Either way button was not displaying multiple times
> [homepage] - Fix showing multiple times the same button. Close #955

- package.json
Update dependency `jsdom` and `engines` so we can run in `node 4.0.0`
> Support node 4.0.0

- bin/dos-db
[`models`](https://github.com/DemocracyOS/democracyos/blob/master/bin/dos-db#L135) tries to import [`./lib/models/forum-reserved-names.js`](https://github.com/DemocracyOS/democracyos/blob/master/lib/models/forum-reserved-names.js) and treat it as a function. This doesn't work.
This adds `forum-reserved-names-.js` to the [list of exceptions to skip](https://github.com/DemocracyOS/democracyos/blob/master/bin/dos-db#L137).
Fixes #1171.
> Adding forum-reserved-names.js

- README.md
The live demo was pointing to a broken link, now points to https://app.democracyos.org/
> Replace broken link in README

- lib/auth-facebook/strategy.js
- lib/translations/lib/pt.json
Apparently the facebook api has changed and it's necessary to specify the fields we want. I've also added the translation to pt for the facebook auth button.
> Fix facebook authentication

- docker/development.Dockerfile
- lib/site/header/component.js
- lib/site/header/header.js
- package.json
After this pull is merged, the imports to another components on front-end should be done using absolute paths from `/lib`.
Before:
```
import user from '../user/user'
```
After:
```
import user from 'lib/user/user'
```
> Add absolute paths

- config/defaults.json
- lib/header/styles.styl
- lib/header/template.jade
- lib/header/view.js
- lib/translations/lib/en.json
Addresses #1285, adds a bar at the bottom that warns if it isn't local or being served over https.
> Add insecure warning to pages

- lib/admin/admin-topics-form/styles.styl
Realigned date and time input fields with the label
from this
to 
by adjusting the jade style sheet.
> #1332 Realigned input fields in 'new topic' form 

- lib/admin/admin-topics-form/view.js
- lib/site/topic-layout/topic-article/comments/parse-comment.js
Add `rel="noopener noreferer" target="_blank"` to markdown text inputs.
> Add link attributes to generated text html output

- docs/install.md
Since the next step is about setting up the configuration file, and the [configuration guide](https://github.com/DemocracyOS/democracyos/blob/master/docs/configuration.md) states that :
> You can generate configuration files using the command:
>
>```
>NODE_ENV=development node ./bin/dos-install --config
>```
The dependencies are then required before to configure. Without it, generating a configuration file leads to : 
```
$ NODE_ENV=development node ./bin/dos-install --config
module.js:472
throw err;
^
Error: Cannot find module 'commander'
```
> add a `make package` install step

- main/api.js
- main/config.js
- main/mongoose.js
- reactions/api/reaction-instance.js
- test/reactions/api/reaction-instance.js
- test/reactions/api/reaction-rule.js
This pull request also fixes a problem in `main.js` where having a .env file with CONFIG.MONGO_URL defined, all the `npm run test` where done with the `dev` DB
```
if (process.env.NODE_ENV === 'test' && !CONFIG.MONGO_URL) {
CONFIG.MONGO_URL = 'mongodb://localhost/DemocracyOS-test'
}
```
Changed to
```
if (process.env.NODE_ENV === 'test' && !CONFIG.MONGO_URL_TEST) {
CONFIG.MONGO_URL = 'mongodb://localhost/DemocracyOS-test'
}
```
Other changes:
* Fixed test issues with reaction rules
* Created API for reaction instances 
* Create tests for reaction instances API 
* Update tests for reaction instances DB-API
> [v3] Add Reaction Instance API, DB-API and Tests

- cms/components/admin.js
- cms/components/navbar.js
- cms/components/posts/post-create.js
- reactions/components/FromCreateContentDialog.js
- reactions/components/reaction-instance.js
- reactions/components/reactions-routes.js
Now the admin panel has reaction instances.
A few changes:
- New panel for reaction instances
- List, Create, Edit (Not working) and Remove components working (we have to discuss this last two)
- Now after creating a post it takes you to create a reaction instance (and it shows a fancy dialog asking if you want to create it) (*)
(*) The strategy is:
1. It redirects to `/reaction-instance/create?fromCreation=true`
2. The `<Create>` component has a "custom field" that checks if the query has a param called `fromCreation`
3. If its true it shows a dialog encouraging the admin to create a reaction instance.
> [v3] Adding reaction instances for the admin panel

- main/api.js
- reactions/api/reaction-vote.js
- reactions/components/ReactionResult.js
- reactions/components/reaction-instance.js
- reactions/components/reaction-rule.js
- reactions/db-api/reaction-instance.js
- reactions/db-api/reaction-vote.js
- reactions/models/reaction-instance.js
- services/reactions.js
- test/reactions/api/reaction-instance.js
- test/reactions/db-api/reaction-instance.js
- test/services/reactions.js
Finally! Added the so waited features needed for reactions feed
The objective was:
The reactions feed should show post cards, with title, summary and reactions count.
When clicked it should show a list of all users that reacted to it.
When a user row is clicked it should navigate to that resource in users admin.
For that we needed an API Service to give us the results. There are 2 types of queries:
- Get the result of a reaction instance
- Get the results for a post (Lets remember, there is no reference from a content -> reaction instance, and besides, this returns an ARRAY of results, cause a content might have more than one reaction instances)
This was needed cause for future uses we will need it to make post cards, not only for the admin panel but also for the webpage.
I made a …
> [v3] Added Reactions Service - Results for Reaction Instances and Posts

- test/cms/api/settings.js
- test/reactions/db-api/reaction-instance.js
Adds a test for /v1.0/api/settings method POST
If a setting is already created in DB, it checks that response is an error with a status code 400 and  a "Bad request" message.
> [v3] Add create settings failing test

- client/admin/components/rest-client.js
- client/site/components/page.js
- client/site/components/post-grid.js
- client/site/components/profile/private-profile.js
- client/site/components/reactions/vote-like-reaction.js
- client/site/components/register/register-form.js
- client/site/components/settings/settings-form.js
- client/utils/fetch-wrapper.js
- cms/api/settings.js
- cms/components/admin.js
- main/index.js
- pages/index.js
- pages/post.js
- pages/profile.js
This PR adds
- Crsf key in rest client of all POST/PUT/DELETE requests
- A fetch wrapper (located at `client/utils/fetch-wrapper`) to add csrf key and credentials to all the fetchs that need it. 
You must import fetchWrapper and then pass it an url and an options object (header and body included). It will return a response or error object.
Please check with care 🌈
> [v3] Add csrf key to all fetchs

- client/admin/components/rest-client.js
- client/site/components/reactions/please-login-modal.js
- client/site/components/reactions/vote-like-reaction.js
- client/site/components/reactions/voting-closed-modal.js
- services/reactions.js
This fix was bound to happen after the merged pull request for authentication.
So basically voting a reaction doesn't need you to tell the API who you are (cause that is not your business, dear user). The server will know if you are a logged user and if not, you will get a FORBIDDEN message.
Any test is appreciated c:
Chiirs!
> [v3] Fix for voting a reaction
